
# Default available language :
# en_uk - English (United Kingdom)
# fr_fr - French (France)
language: "en_uk"

chat:
#  anyname:
#    command: "your_command"
#    aliases:
#      - "your_alias"
#    prefix: "§8[§6§lA command§8] "
#    format: "{PREFIX} §7{PLAYER} §8» §7{MESSAGE}"
#    permission:
#      write: "fluix.chat.your_command.write"
#      read: "fluix.chat.your_command.read"
  default:
    command: "default"
    aliases:
      - "d"
    prefix: "§8[§6§lDefault§8] "
    format: "{PREFIX} §7{PLAYER} §8» §7{MESSAGE}"
    permission:
      write: "fluix.chat.default.write"
      read: "fluix.chat.default.read"


# Placeholders :
# Placeholders are used to replace the value with the actual value.
# It is only available in the format section.
# {PLAYER} - Player name
# {MESSAGE} - Message to be sent
# {PREFIX} - Prefix of the chat
# {SERVER} - Server name where the message is sent
